import { NextResponse } from "next/server";
import { reportSubtitleFailure } from "@/lib/monitor";
import { redis } from "@/lib/redis";

export const dynamic = "force-dynamic";

const APIFY_ACTOR_URL =
  "https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items";
const SUBTITLE_CACHE_TTL = 86400;

type SubtitleCue = {
  start: number;
  dur: number;
  text: string;
};

type ApifySubtitleTrack = {
  srtUrl?: string | null;
  type?: string;
  language?: string;
  srt?: string | null;
};

type ApifyVideoItem = {
  subtitles?: ApifySubtitleTrack[] | null;
};

function parseSrtTime(timeStr: string): number {
  const [timePart, msPart] = timeStr.split(",");
  const [h, m, s] = timePart.split(":").map(Number);
  return h * 3600 + m * 60 + s + Number(msPart) / 1000;
}

function parseSrt(srt: string): SubtitleCue[] {
  const blocks = srt.trim().split(/\n\n+/);
  const cues: SubtitleCue[] = [];

  for (const block of blocks) {
    const lines = block.trim().split("\n");
    const timingLineIndex = lines.findIndex((l) =>
      /\d{2}:\d{2}:\d{2},\d{3}\s*-->\s*\d{2}:\d{2}:\d{2},\d{3}/.test(l)
    );

    if (timingLineIndex === -1) {
      continue;
    }

    const timingMatch = lines[timingLineIndex].match(
      /(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/
    );

    if (!timingMatch) {
      continue;
    }

    const start = parseSrtTime(timingMatch[1]);
    const end = parseSrtTime(timingMatch[2]);
    const dur = end - start;
    const text = lines
      .slice(timingLineIndex + 1)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();

    if (text && Number.isFinite(start) && Number.isFinite(dur) && dur > 0) {
      cues.push({ start, dur, text });
    }
  }

  return cues;
}

async function fetchFromApify(videoId: string, lang: string): Promise<SubtitleCue[]> {
  const token = process.env.APIFY_API_TOKEN;

  if (!token) {
    console.error("[subtitle] APIFY_API_TOKEN not set");
    return [];
  }

  const url = `${APIFY_ACTOR_URL}?token=${token}&timeout=55&memory=256`;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      startUrls: [{ url: `https://www.youtube.com/watch?v=${videoId}` }],
      downloadSubtitles: true,
      subtitlesLanguage: lang,
      subtitlesFormat: "srt",
      preferAutoGeneratedSubtitles: false,
      maxResults: 1
    }),
    signal: AbortSignal.timeout(60000)
  });

  if (!response.ok) {
    console.error("[subtitle] Apify request failed:", response.status);
    return [];
  }

  const items = (await response.json()) as ApifyVideoItem[];
  const firstItem = items[0];

  if (!firstItem?.subtitles?.length) {
    console.log("[subtitle] Apify: no subtitles for", videoId);
    return [];
  }

  const langPrefix = lang.split("-")[0];
  const track =
    firstItem.subtitles.find((t) => t.language === lang) ??
    firstItem.subtitles.find((t) => t.language?.startsWith(langPrefix)) ??
    firstItem.subtitles[0];

  if (!track?.srt) {
    console.log("[subtitle] Apify: no SRT content for", videoId, lang);
    return [];
  }

  const cues = parseSrt(track.srt);
  console.log("[subtitle] Apify fetched", cues.length, "cues for", videoId, lang);
  return cues;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const videoId = searchParams.get("v")?.trim() ?? "";
  const lang = searchParams.get("lang")?.trim() || "es";

  if (!videoId) {
    return NextResponse.json([], { status: 200 });
  }

  // v2: switched to preferAutoGeneratedSubtitles=false so manual tracks win
  // when available; bump key so old ASR-only caches are not reused.
  const cacheKey = `subtitle:v2:${videoId}:${lang}`;

  try {
    const cached = await redis.get(cacheKey);

    if (cached) {
      return NextResponse.json(JSON.parse(cached) as SubtitleCue[], {
        headers: { "Cache-Control": "s-maxage=86400, stale-while-revalidate=3600" }
      });
    }
  } catch {
    // Redis unavailable, fall through to Apify
  }

  try {
    const cues = await fetchFromApify(videoId, lang);

    if (cues.length > 0) {
      try {
        await redis.set(cacheKey, JSON.stringify(cues), "EX", SUBTITLE_CACHE_TTL);
      } catch {
        // Redis write failed, still return cues
      }
    }

    return NextResponse.json(cues, {
      headers: { "Cache-Control": "s-maxage=86400, stale-while-revalidate=3600" }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("[subtitle] fetch failed:", message);
    reportSubtitleFailure(videoId, error);
    return NextResponse.json([], { status: 200 });
  }
}
