import { NextResponse } from "next/server";
import { getLocalWhisperSubtitles } from "@/lib/localWhisper";
import { reportSubtitleFailure } from "@/lib/monitor";
import { redis } from "@/lib/redis";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const APIFY_ACTOR_URL =
  "https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items";
const SUBTITLE_CACHE_TTL = 86400;
const MIN_REASONABLE_CUE_COUNT = 6;
const MAX_REASONABLE_CUE_GAP_SEC = 25;

type SubtitleCue = {
  start: number;
  dur: number;
  text: string;
};

type SubtitleHint = {
  reason: "no_subtitle";
};

// Provenance of the returned subtitle cues, exposed via the `source` field
// and the `X-Subtitle-Source` response header so it's easy to tell whether
// the displayed subtitles came from the browser-extension capture (accurate
// YouTube native captions) vs the Apify/Whisper server fallbacks.
type SubtitleSource = "extension" | "apify" | "whisper" | "cache" | "none";

type SubtitleResponse = {
  cues: SubtitleCue[];
  hint?: SubtitleHint;
  source?: SubtitleSource;
};

// Envelope stored in Redis so cached entries carry their provenance. Older
// entries are bare cue arrays (no source) — treated as "cache".
type CachedSubtitlePayload = {
  cues: SubtitleCue[];
  source: SubtitleSource;
  at?: number;
};

type ApifySubtitleTrack = {
  srtUrl?: string | null;
  type?: string;
  language?: string;
  srt?: string | null;
};

type ApifyVideoItem = {
  subtitles?: ApifySubtitleTrack[] | null;
};

/**
 * YouTube auto-caption (ASR) tracks use a rolling format where each cue's
 * duration overlaps the next cue (so lines "scroll" on screen). With
 * overlapping cues, time-based active-cue lookup picks the wrong (earlier)
 * line and the subtitle appears out of sync. Clamp each cue's end to the
 * next cue's start so cues are sequential and non-overlapping, while
 * preserving genuine gaps (silence/music).
 */
function clampOverlappingCues(cues: SubtitleCue[]): SubtitleCue[] {
  const sorted = [...cues]
    .filter((cue) => Number.isFinite(cue?.start) && Number.isFinite(cue?.dur))
    .sort((a, b) => a.start - b.start);

  for (let i = 0; i < sorted.length - 1; i += 1) {
    const nextStart = sorted[i + 1].start;
    const end = sorted[i].start + sorted[i].dur;
    if (end > nextStart) {
      sorted[i] = { ...sorted[i], dur: Math.max(0, nextStart - sorted[i].start) };
    }
  }

  return sorted;
}

function parseSrtTime(timeStr: string): number {
  const [timePart, msPart] = timeStr.split(",");
  const [h, m, s] = timePart.split(":").map(Number);
  return h * 3600 + m * 60 + s + Number(msPart) / 1000;
}

function parseSrt(srt: string): SubtitleCue[] {
  const blocks = srt.trim().split(/\n\n+/);
  const cues: SubtitleCue[] = [];

  for (const block of blocks) {
    const lines = block.trim().split("\n");
    const timingLineIndex = lines.findIndex((l) =>
      /\d{2}:\d{2}:\d{2},\d{3}\s*-->\s*\d{2}:\d{2}:\d{2},\d{3}/.test(l)
    );

    if (timingLineIndex === -1) {
      continue;
    }

    const timingMatch = lines[timingLineIndex].match(
      /(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/
    );

    if (!timingMatch) {
      continue;
    }

    const start = parseSrtTime(timingMatch[1]);
    const end = parseSrtTime(timingMatch[2]);
    const dur = end - start;
    const text = lines
      .slice(timingLineIndex + 1)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();

    if (text && Number.isFinite(start) && Number.isFinite(dur) && dur > 0) {
      cues.push({ start, dur, text });
    }
  }

  return cues;
}

async function callApify(
  videoId: string,
  lang: string,
  preferAuto: boolean
): Promise<SubtitleCue[]> {
  const token = process.env.APIFY_API_TOKEN;

  if (!token) {
    console.error("[subtitle] APIFY_API_TOKEN not set");
    return [];
  }

  const url = `${APIFY_ACTOR_URL}?token=${token}&timeout=55&memory=256`;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      startUrls: [{ url: `https://www.youtube.com/watch?v=${videoId}` }],
      downloadSubtitles: true,
      subtitlesLanguage: lang,
      subtitlesFormat: "srt",
      preferAutoGeneratedSubtitles: preferAuto,
      maxResults: 1
    }),
    signal: AbortSignal.timeout(60000)
  });

  if (!response.ok) {
    console.error(
      "[subtitle] Apify request failed:",
      response.status,
      preferAuto ? "asr" : "manual"
    );
    return [];
  }

  const items = (await response.json()) as ApifyVideoItem[];
  const firstItem = items[0];

  if (!firstItem?.subtitles?.length) {
    return [];
  }

  const langPrefix = lang.split("-")[0];
  const track =
    firstItem.subtitles.find((t) => t.language === lang) ??
    firstItem.subtitles.find((t) => t.language?.startsWith(langPrefix)) ??
    firstItem.subtitles[0];

  if (!track?.srt) {
    return [];
  }

  return parseSrt(track.srt);
}

/**
 * Merge manual cues with ASR cues so the final track has no gaps.
 *
 * Strategy:
 *   - Manual cues take absolute priority (higher quality).
 *   - For each ASR cue, keep it only if its center timestamp does NOT
 *     fall inside any manual cue's [start, start+dur] range.
 *   - Sort the union by start time.
 *
 * This handles the common "manual subs only cover intro" pattern: we keep
 * the curated intro intact and let ASR fill the rest of the video.
 */
function mergeManualWithAsr(
  manualCues: SubtitleCue[],
  asrCues: SubtitleCue[]
): SubtitleCue[] {
  if (manualCues.length === 0) return asrCues;
  if (asrCues.length === 0) return manualCues;

  const manualRanges = manualCues
    .map((cue) => [cue.start, cue.start + cue.dur] as const)
    .sort((a, b) => a[0] - b[0]);

  const isCovered = (timestamp: number) => {
    // Binary-search-friendly linear scan; manualRanges is usually < 1k entries.
    for (const [rangeStart, rangeEnd] of manualRanges) {
      if (timestamp < rangeStart) return false;
      if (timestamp <= rangeEnd) return true;
    }
    return false;
  };

  const asrFill = asrCues.filter((cue) => {
    const center = cue.start + cue.dur / 2;
    return !isCovered(center);
  });

  return [...manualCues, ...asrFill].sort((a, b) => a.start - b.start);
}

async function fetchHybridSubtitles(
  videoId: string,
  lang: string
): Promise<SubtitleCue[]> {
  // Pull both manual and ASR tracks in parallel. preferAutoGeneratedSubtitles
  // is the only knob Apify gives us to disambiguate between them when both
  // exist on a video; flip it twice to get each.
  const [manualCues, asrCues] = await Promise.all([
    callApify(videoId, lang, false).catch((error) => {
      console.warn("[subtitle] manual fetch failed:", error);
      return [] as SubtitleCue[];
    }),
    callApify(videoId, lang, true).catch((error) => {
      console.warn("[subtitle] asr fetch failed:", error);
      return [] as SubtitleCue[];
    })
  ]);

  const merged = mergeManualWithAsr(manualCues, asrCues);

  console.log(
    "[subtitle] Apify fetched",
    merged.length,
    "cues for",
    videoId,
    lang,
    `(manual=${manualCues.length}, asr=${asrCues.length})`
  );

  return merged;
}

function getMaxCueGap(cues: SubtitleCue[]): number {
  const sorted = [...cues].sort((a, b) => a.start - b.start);
  let maxGap = 0;

  for (let i = 1; i < sorted.length; i += 1) {
    const previousEnd = sorted[i - 1].start + sorted[i - 1].dur;
    maxGap = Math.max(maxGap, sorted[i].start - previousEnd);
  }

  return maxGap;
}

function shouldUseWhisperFallback(
  cues: SubtitleCue[],
  forceWhisper: boolean
): boolean {
  if (forceWhisper) return true;
  if (cues.length === 0) return true;
  if (cues.length < MIN_REASONABLE_CUE_COUNT) return true;

  return getMaxCueGap(cues) > MAX_REASONABLE_CUE_GAP_SEC;
}

async function fetchSubtitlesWithFallback(
  videoId: string,
  lang: string,
  forceWhisper: boolean
): Promise<{ cues: SubtitleCue[]; source: SubtitleSource }> {
  const apifyCues = forceWhisper ? [] : await fetchHybridSubtitles(videoId, lang);

  if (!shouldUseWhisperFallback(apifyCues, forceWhisper)) {
    return { cues: apifyCues, source: "apify" };
  }

  try {
    const whisperCues = await getLocalWhisperSubtitles(videoId, lang);

    if (whisperCues.length > 0) {
      console.log(
        "[subtitle] Whisper fetched",
        whisperCues.length,
        "cues for",
        videoId,
        lang
      );
      return { cues: whisperCues, source: "whisper" };
    }
  } catch (error) {
    console.warn("[subtitle] Whisper fallback failed:", error);
  }

  return { cues: apifyCues, source: apifyCues.length > 0 ? "apify" : "none" };
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const videoId = searchParams.get("v")?.trim() ?? "";
  const lang = searchParams.get("lang")?.trim() || "es";
  const forceWhisper = searchParams.get("forceWhisper") === "1";

  if (!videoId) {
    return NextResponse.json({ cues: [] satisfies SubtitleCue[] }, { status: 200 });
  }

  // v3: hybrid manual + ASR merge. Bump key so v2 (manual-only) caches
  // are not reused — those entries may have gaps where manual stopped.
  const cacheKey = `subtitle:v4:${videoId}:${lang}:${forceWhisper ? "whisper" : "auto"}`;

  try {
    const cached = await redis.get(cacheKey);

    if (cached) {
      const parsed = JSON.parse(cached) as CachedSubtitlePayload | SubtitleCue[];
      const isEnvelope = !Array.isArray(parsed) && Array.isArray(parsed.cues);
      const cues = isEnvelope ? (parsed as CachedSubtitlePayload).cues : (parsed as SubtitleCue[]);
      const source: SubtitleSource = isEnvelope
        ? (parsed as CachedSubtitlePayload).source ?? "cache"
        : "cache";

      return NextResponse.json(
        { cues: clampOverlappingCues(cues), source } satisfies SubtitleResponse,
        {
          headers: { "Cache-Control": "no-store", "X-Subtitle-Source": source }
        }
      );
    }
  } catch {
    // Redis unavailable, fall through to Apify
  }

  try {
    const { cues, source } = await fetchSubtitlesWithFallback(videoId, lang, forceWhisper);

    if (cues.length > 0) {
      try {
        const envelope: CachedSubtitlePayload = { cues, source, at: Date.now() };
        await redis.set(cacheKey, JSON.stringify(envelope), "EX", SUBTITLE_CACHE_TTL);
      } catch {
        // Redis write failed, still return cues
      }
    }

    const payload: SubtitleResponse =
      cues.length > 0
        ? { cues: clampOverlappingCues(cues), source }
        : { cues: [], hint: { reason: "no_subtitle" }, source: "none" };

    return NextResponse.json(payload, {
      headers: { "Cache-Control": "no-store", "X-Subtitle-Source": source }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("[subtitle] fetch failed:", message);
    reportSubtitleFailure(videoId, error);
    return NextResponse.json(
      { cues: [], hint: { reason: "no_subtitle" } } satisfies SubtitleResponse,
      { status: 200 }
    );
  }
}
