import { NextResponse } from "next/server";
import { reportSubtitleFailure } from "@/lib/monitor";
import { redis } from "@/lib/redis";

export const dynamic = "force-dynamic";

const APIFY_ACTOR_URL =
  "https://api.apify.com/v2/acts/streamers~youtube-scraper/run-sync-get-dataset-items";
const SUBTITLE_CACHE_TTL = 86400;

type SubtitleCue = {
  start: number;
  dur: number;
  text: string;
};

type ApifySubtitleTrack = {
  srtUrl?: string | null;
  type?: string;
  language?: string;
  srt?: string | null;
};

type ApifyVideoItem = {
  subtitles?: ApifySubtitleTrack[] | null;
};

function parseSrtTime(timeStr: string): number {
  const [timePart, msPart] = timeStr.split(",");
  const [h, m, s] = timePart.split(":").map(Number);
  return h * 3600 + m * 60 + s + Number(msPart) / 1000;
}

function parseSrt(srt: string): SubtitleCue[] {
  const blocks = srt.trim().split(/\n\n+/);
  const cues: SubtitleCue[] = [];

  for (const block of blocks) {
    const lines = block.trim().split("\n");
    const timingLineIndex = lines.findIndex((l) =>
      /\d{2}:\d{2}:\d{2},\d{3}\s*-->\s*\d{2}:\d{2}:\d{2},\d{3}/.test(l)
    );

    if (timingLineIndex === -1) {
      continue;
    }

    const timingMatch = lines[timingLineIndex].match(
      /(\d{2}:\d{2}:\d{2},\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2},\d{3})/
    );

    if (!timingMatch) {
      continue;
    }

    const start = parseSrtTime(timingMatch[1]);
    const end = parseSrtTime(timingMatch[2]);
    const dur = end - start;
    const text = lines
      .slice(timingLineIndex + 1)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();

    if (text && Number.isFinite(start) && Number.isFinite(dur) && dur > 0) {
      cues.push({ start, dur, text });
    }
  }

  return cues;
}

async function callApify(
  videoId: string,
  lang: string,
  preferAuto: boolean
): Promise<SubtitleCue[]> {
  const token = process.env.APIFY_API_TOKEN;

  if (!token) {
    console.error("[subtitle] APIFY_API_TOKEN not set");
    return [];
  }

  const url = `${APIFY_ACTOR_URL}?token=${token}&timeout=55&memory=256`;
  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      startUrls: [{ url: `https://www.youtube.com/watch?v=${videoId}` }],
      downloadSubtitles: true,
      subtitlesLanguage: lang,
      subtitlesFormat: "srt",
      preferAutoGeneratedSubtitles: preferAuto,
      maxResults: 1
    }),
    signal: AbortSignal.timeout(60000)
  });

  if (!response.ok) {
    console.error(
      "[subtitle] Apify request failed:",
      response.status,
      preferAuto ? "asr" : "manual"
    );
    return [];
  }

  const items = (await response.json()) as ApifyVideoItem[];
  const firstItem = items[0];

  if (!firstItem?.subtitles?.length) {
    return [];
  }

  const langPrefix = lang.split("-")[0];
  const track =
    firstItem.subtitles.find((t) => t.language === lang) ??
    firstItem.subtitles.find((t) => t.language?.startsWith(langPrefix)) ??
    firstItem.subtitles[0];

  if (!track?.srt) {
    return [];
  }

  return parseSrt(track.srt);
}

/**
 * Merge manual cues with ASR cues so the final track has no gaps.
 *
 * Strategy:
 *   - Manual cues take absolute priority (higher quality).
 *   - For each ASR cue, keep it only if its center timestamp does NOT
 *     fall inside any manual cue's [start, start+dur] range.
 *   - Sort the union by start time.
 *
 * This handles the common "manual subs only cover intro" pattern: we keep
 * the curated intro intact and let ASR fill the rest of the video.
 */
function mergeManualWithAsr(
  manualCues: SubtitleCue[],
  asrCues: SubtitleCue[]
): SubtitleCue[] {
  if (manualCues.length === 0) return asrCues;
  if (asrCues.length === 0) return manualCues;

  const manualRanges = manualCues
    .map((cue) => [cue.start, cue.start + cue.dur] as const)
    .sort((a, b) => a[0] - b[0]);

  const isCovered = (timestamp: number) => {
    // Binary-search-friendly linear scan; manualRanges is usually < 1k entries.
    for (const [rangeStart, rangeEnd] of manualRanges) {
      if (timestamp < rangeStart) return false;
      if (timestamp <= rangeEnd) return true;
    }
    return false;
  };

  const asrFill = asrCues.filter((cue) => {
    const center = cue.start + cue.dur / 2;
    return !isCovered(center);
  });

  return [...manualCues, ...asrFill].sort((a, b) => a.start - b.start);
}

async function fetchHybridSubtitles(
  videoId: string,
  lang: string
): Promise<SubtitleCue[]> {
  // Pull both manual and ASR tracks in parallel. preferAutoGeneratedSubtitles
  // is the only knob Apify gives us to disambiguate between them when both
  // exist on a video; flip it twice to get each.
  const [manualCues, asrCues] = await Promise.all([
    callApify(videoId, lang, false).catch((error) => {
      console.warn("[subtitle] manual fetch failed:", error);
      return [] as SubtitleCue[];
    }),
    callApify(videoId, lang, true).catch((error) => {
      console.warn("[subtitle] asr fetch failed:", error);
      return [] as SubtitleCue[];
    })
  ]);

  const merged = mergeManualWithAsr(manualCues, asrCues);

  console.log(
    "[subtitle] Apify fetched",
    merged.length,
    "cues for",
    videoId,
    lang,
    `(manual=${manualCues.length}, asr=${asrCues.length})`
  );

  return merged;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const videoId = searchParams.get("v")?.trim() ?? "";
  const lang = searchParams.get("lang")?.trim() || "es";

  if (!videoId) {
    return NextResponse.json([], { status: 200 });
  }

  // v3: hybrid manual + ASR merge. Bump key so v2 (manual-only) caches
  // are not reused — those entries may have gaps where manual stopped.
  const cacheKey = `subtitle:v3:${videoId}:${lang}`;

  try {
    const cached = await redis.get(cacheKey);

    if (cached) {
      return NextResponse.json(JSON.parse(cached) as SubtitleCue[], {
        headers: { "Cache-Control": "s-maxage=86400, stale-while-revalidate=3600" }
      });
    }
  } catch {
    // Redis unavailable, fall through to Apify
  }

  try {
    const cues = await fetchHybridSubtitles(videoId, lang);

    if (cues.length > 0) {
      try {
        await redis.set(cacheKey, JSON.stringify(cues), "EX", SUBTITLE_CACHE_TTL);
      } catch {
        // Redis write failed, still return cues
      }
    }

    return NextResponse.json(cues, {
      headers: { "Cache-Control": "s-maxage=86400, stale-while-revalidate=3600" }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("[subtitle] fetch failed:", message);
    reportSubtitleFailure(videoId, error);
    return NextResponse.json([], { status: 200 });
  }
}
